dist: trusty
sudo: required
language: python
# The travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable.
python: 3.5
services: docker

branches:
  only:
    - master
    # We want to build wip/* branches since these are not usually used for PRs
    - /^wip\/.*$/
    # We want to build version tags as well.
    - /^v\d+\.\d+.*$/

env:
  global:
    # directory containing the project source
    - REPO_DIR=.
    # pip dependencies to _build_ project
    # - BUILD_DEPENDS="..."
    # pip dependencies to _test_ project
    - TEST_DEPENDS="-rdev-requirements.txt"
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    # the pypi password is stored in Travis settings
    - TWINE_USERNAME="adobe-type-tools-ci"

matrix:
  fast_finish: true
  exclude:
    # Exclude the default Python 3.5 build
    - python: 3.5
  include:
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=2.7
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.6
    #     - BUILD_SDIST=true
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.7
    # - os: linux
    #   before_install: false
    #   install:
    #     - pip install tox
    #   script:
    #     - tox -e coverage-codecov-c
    #   after_success: false
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
    # - os: linux
    #   before_install: false
    #   install:
    #     - pip3 install meson ninja
    #   script:
    #     - meson build libpsautohint
    #     - ninja -C build
    #     - ls build
    #     - build/autohintexe -h
    #   after_success: false

cache: pip

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - build_wheel $REPO_DIR $PLAT

script:
  # - install_run $PLAT
  - ls wheelhouse/psautohint*.whl

# after_success:
  # - pip install tox
  # upload code coverage to Codecov.io
  # - tox -e codecov
  # # deploy to PyPI on tags
  # - |
  #   if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "adobe-type-tools/psautohint" ]; then
  #     pip install --upgrade twine
  #     twine upload wheelhouse/psautohint*.whl
  #     if [ "$BUILD_SDIST" == true ]; then
  #       tox -e sdist
  #       twine upload dist/psautohint*.zip
  #     fi
  #   fi

deploy:
  # deploy to Github Releases on tags
  provider: releases
  api_key:
    secure: OwLpOtn4ZHEHhNrTKiDyetJKyLVtAAoNBJ/OUAlv8+7eiFhzU8v2sM672WE9iyFJGGKfgxId0QMec7KMqRpVgMxJJcwbWe/a91HdCgM20dytat9HhjHaQlpMjqoUZ7wFlY0JGAXBH+Lnmx86V07fMvDg0Ht6Ha3FRln4EAL61B4SYoeoWG5/1UDOE8cy7O0UhWP93QxQmYtizaESVHeayGyxI2Y4s9TJA5ezwpe6XEflX1Q6OOBTO3AnMjmm+MZaYn3FjL8TsYTHk2QlKokhmk5DZEjwLLvVMN8nBGgLnc2HhD7o9vFbEGw+ZJ4rxzE27a/nC/Esz2/oEZXMPJe3yNwXSR6jyzQJTfKvAqHANh8u3n02g2AzghfhZQJwwtisperQ7vI8jKZ5p6RqnUg3rCCOT9l8J70boNPHSvxH5EP7KQxJSArOJmsikaI+8ZwRKuCqHepqFlH3WVYPw0AVgrTzQIcDAJcEqLXZSzgDu7McFcW+03TSjMN++lX1dQCl0buWPLCn4Sot+W4/zsREvHilukJdr3RJeeLPgsJ5ONRYTmg6caxBo3o5An9cOwnluTCFjbLWPGraj+xC+6pxKu7D8zFfJHlxPLJPKdT8mfBNxsnh8QwLH9XEQh4MgDuvVKoE0tOmy1ery804hpN6xbiLiYg3ro7IiwbQZWsD6c8=
  skip_cleanup: true
  file_glob: true
  file: "wheelhouse/psautohint*.whl"
  on:
    tags: true
    repo: anthrotype/psautohint
    all_branches: true
    condition: "$BUILD_SDIST == true"
